POST http://localhost:5001/api/notes
Content-Type: application/json

{
  "title": "new note",
  "content": "bar"
}

###

GET http://localhost:5001/api/notes

###

GET http://localhost:5001/api/notes/684c43564b6f3200cb9a46e3


###

PUT http://localhost:5001/api/notes/684c3e48f426a9703d878579
Content-Type: application/json

{
  "title": "updated title",
  "content": "updated content"
}


###

DELETE http://localhost:5001/api/notes/684c3e48f426a9703d878579